/**
 * Seed campaign: "Synthetic Reality vs Provenance"
 * Nested filmstrips demonstrate recursive depth + fork readiness.
 */

import { computeHeatBps, makeScene } from "./filmstrip.js";

function scene(partial) {
  const s = makeScene(partial);
  // Recompute heat from signals when not explicitly locked by rich seed
  if (partial.heatBps == null) {
    s.heatBps = computeHeatBps(s);
  }
  return s;
}

export function buildSeedCampaign() {
  /** @type {Record<string, import('./filmstrip.js').Filmstrip>} */
  const strips = {};
  /** @type {Record<string, import('./filmstrip.js').Scene>} */
  const scenes = {};

  const rootId = "strip-root";
  strips[rootId] = {
    id: rootId,
    title: "Synthetic Reality vs Provenance",
    campaign: "Active Campaign · Theatre Map",
    kind: "root",
    parentSceneId: null,
    sceneIds: ["s01", "s02", "s03", "s04", "s05", "s06", "s07", "s08"],
    mode: "async",
  };

  // Branch under s03 — evidence dive
  const evidenceStrip = "strip-evidence-s03";
  strips[evidenceStrip] = {
    id: evidenceStrip,
    title: "Evidence dive · Receipt chains",
    campaign: "Branch · Provenance mechanics",
    kind: "branch",
    parentSceneId: "s03",
    sceneIds: ["e01", "e02", "e03", "e04"],
    mode: "async",
  };

  // Branch under s05 — institutional capture
  const captureStrip = "strip-capture-s05";
  strips[captureStrip] = {
    id: captureStrip,
    title: "Sub-argument · Institutional capture",
    campaign: "Branch · Fourth Estate failure modes",
    kind: "branch",
    parentSceneId: "s05",
    sceneIds: ["c01", "c02", "c03"],
    mode: "async",
  };

  // Historical precedent under s02
  const histStrip = "strip-hist-s02";
  strips[histStrip] = {
    id: histStrip,
    title: "Precedent · Memory-holing before crypto",
    campaign: "Branch · Historical terrain",
    kind: "branch",
    parentSceneId: "s02",
    sceneIds: ["h01", "h02", "h03"],
    mode: "async",
  };

  // Nested branch under e02
  const deepStrip = "strip-deep-e02";
  strips[deepStrip] = {
    id: deepStrip,
    title: "Deep · Hash linkage failure modes",
    campaign: "Branch · Recursive depth",
    kind: "branch",
    parentSceneId: "e02",
    sceneIds: ["d01", "d02"],
    mode: "async",
  };

  const rootScenes = [
    scene({
      id: "s01",
      filmstripId: rootId,
      title: "Opening gambit",
      move: "assertion",
      durationSec: 52,
      speaker: "Strategist",
      openHook: "Generation is cheap. History is expensive.",
      core: "When synthetic media can fabricate any scene, the decisive terrain is not persuasion — it is provenance. Without a durable chain, the public cannot tell performance from record.",
      closeHook: "So what breaks first when memory is optional?",
      viewThroughBps: 8200,
      rewatchBps: 4100,
      exploreSeconds: 240,
      crossRefs: 3,
      highMeritSignals: 2,
      heatBps: 7100,
      meritBps: 4200,
      tags: {
        claims: ["Provenance is decisive terrain"],
        entities: ["Synthetic media", "Public memory"],
        function: "assertion",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["provenance", "media"],
      },
    }),
    scene({
      id: "s02",
      filmstripId: rootId,
      title: "The memory-hole problem",
      move: "evidence",
      durationSec: 68,
      speaker: "Chronicler",
      openHook: "Quiet revision is older than the feed.",
      core: "Pre-cryptographic institutions could revise the archive without a public scar. Screenshots aged poorly. Retractions vanished. The Living Log exists so expression is harder to erase and harder to rewrite.",
      closeHook: "Go deeper for historical precedent — or advance.",
      viewThroughBps: 7600,
      rewatchBps: 5200,
      branchDepthCount: 3,
      exploreSeconds: 400,
      crossRefs: 5,
      highMeritSignals: 3,
      heatBps: 8400,
      meritBps: 5100,
      branchFilmstripIds: [histStrip],
      logBound: true,
      tags: {
        claims: ["Silent erasure is a structural failure of prior press"],
        entities: ["Living Log", "Archives", "First Amendment"],
        function: "evidence",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["record", "press"],
      },
    }),
    scene({
      id: "s03",
      filmstripId: rootId,
      title: "Receipts as weapons",
      move: "assertion",
      durationSec: 61,
      speaker: "Combatant",
      openHook: "A hash is not a vibe.",
      core: "Receipt chains turn claims into inspectable objects. Broken links are labeled, never papered over. That is how intellectual combat stays accountable under pressure.",
      closeHook: "Dive the evidence branch — see failure modes.",
      viewThroughBps: 7900,
      rewatchBps: 4800,
      branchDepthCount: 4,
      forkCount: 2,
      exploreSeconds: 520,
      crossRefs: 4,
      highMeritSignals: 4,
      heatBps: 9100,
      meritBps: 6200,
      criticalNode: true,
      branchFilmstripIds: [evidenceStrip],
      logBound: true,
      tags: {
        claims: ["Broken chains must be labeled"],
        entities: ["Receipt hash", "EXOCHAIN", "IW-8"],
        function: "assertion",
        epistemic: "well_supported",
        temperature: "confrontational",
        domains: ["provenance", "kernel"],
      },
    }),
    scene({
      id: "s04",
      filmstripId: rootId,
      title: "Counter · Theatre without substance",
      move: "rebuttal",
      durationSec: 58,
      speaker: "Adversary",
      openHook: "Spectacle can mimic rigor.",
      core: "A beautiful filmstrip that never binds to the Log is costume. Engagement heat without merit is another attention farm. The constitutional shell must fail closed — or the theatre lies.",
      closeHook: "Hold that tension. Capture is next.",
      viewThroughBps: 7000,
      rewatchBps: 3900,
      forkCount: 1,
      exploreSeconds: 310,
      crossRefs: 2,
      highMeritSignals: 2,
      heatBps: 6800,
      meritBps: 4700,
      tags: {
        claims: ["Heat without Log binding is costume"],
        entities: ["Filmstrip", "Living Log", "trust_claim"],
        function: "rebuttal",
        epistemic: "contested",
        temperature: "confrontational",
        domains: ["merit", "trust"],
      },
    }),
    scene({
      id: "s05",
      filmstripId: rootId,
      title: "Capture vs chaos",
      move: "reframe",
      durationSec: 72,
      speaker: "Analyst",
      openHook: "Two failure modes. One trap.",
      core: "Capture subordinates inquiry to power. Chaos floods the zone with low-rigor noise. The harder middle — free, rigorous, permanent — is the press posture. Visual theatre must serve that middle, not replace it.",
      closeHook: "Branch into institutional capture patterns.",
      viewThroughBps: 7400,
      rewatchBps: 4500,
      branchDepthCount: 3,
      exploreSeconds: 380,
      crossRefs: 6,
      highMeritSignals: 3,
      heatBps: 7800,
      meritBps: 5500,
      branchFilmstripIds: [captureStrip],
      tags: {
        claims: ["Capture and chaos both destroy clear thought"],
        entities: ["Fourth Estate", "intelwar.press"],
        function: "reframe",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["press", "governance"],
      },
    }),
    scene({
      id: "s06",
      filmstripId: rootId,
      title: "Multi-intelligence under rules",
      move: "assertion",
      durationSec: 64,
      speaker: "Cross-Checker",
      openHook: "AI is already in the arena.",
      core: "Unattested synthetic voice is noise. Declared AI participation under consent, human override, and Log binding is combat under rules. Autotagging and adversarial analysis are instruments — not oracles.",
      closeHook: "Fork here for AI micro-debate.",
      viewThroughBps: 7200,
      rewatchBps: 4300,
      forkCount: 3,
      exploreSeconds: 290,
      crossRefs: 3,
      highMeritSignals: 5,
      heatBps: 8000,
      meritBps: 6400,
      tags: {
        claims: ["Synthetic voices must declare themselves"],
        entities: ["0dentity", "CrossCheck", "Human Override"],
        function: "assertion",
        epistemic: "emerging",
        temperature: "analytical",
        domains: ["ai", "merit"],
      },
    }),
    scene({
      id: "s07",
      filmstripId: rootId,
      title: "Heat is not truth",
      move: "concession",
      durationSec: 49,
      speaker: "Moderator",
      openHook: "Intensity concentrates. Carefully.",
      core: "Heat maps where rigorous attention gathers. It must not become automated truth scoring. Hot nodes invite scrutiny; cold nodes may still be correct. Merit rewards survival under adversarial pressure — not applause.",
      closeHook: "Watch the heat board. Then the close.",
      viewThroughBps: 6500,
      rewatchBps: 3000,
      exploreSeconds: 200,
      highMeritSignals: 2,
      heatBps: 5400,
      meritBps: 3900,
      tags: {
        claims: ["Heat surfaces attention; merit surfaces rigor"],
        entities: ["Heat map", "0dentity"],
        function: "concession",
        epistemic: "well_supported",
        temperature: "synthetic",
        domains: ["metrics", "merit"],
      },
    }),
    scene({
      id: "s08",
      filmstripId: rootId,
      title: "Close · Enter with intention",
      move: "synthesis",
      durationSec: 56,
      speaker: "Arena",
      openHook: "The filmstrip is navigable memory.",
      core: "Horizontal time. Recursive depth. In-situ forks. Significant scenes bind to the Living Log with consent and provenance. The theatre showcases media and interaction — the Record preserves constitutional guarantees.",
      closeHook: "Deploy to Log, Press, or CrossCheck.",
      viewThroughBps: 6900,
      rewatchBps: 3600,
      exploreSeconds: 180,
      crossRefs: 4,
      highMeritSignals: 3,
      heatBps: 6200,
      meritBps: 5000,
      logBound: true,
      tags: {
        claims: ["Filmstrip experiences; Log endures"],
        entities: ["Living Log", "intelwar.tv", "intelwar.net"],
        function: "synthesis",
        epistemic: "well_supported",
        temperature: "synthetic",
        domains: ["theatre", "record"],
      },
    }),
  ];

  for (const s of rootScenes) scenes[s.id] = s;

  // Evidence branch
  for (const s of [
    scene({
      id: "e01",
      filmstripId: evidenceStrip,
      title: "Anatomy of a receipt",
      move: "evidence",
      durationSec: 54,
      parentSceneId: "s03",
      openHook: "One entry. Many links.",
      core: "content_hash, receipt_hash, previous_receipt_hash, dag_node_hash — each is a grip point. Missing previous breaks the chain visibly.",
      closeHook: "What happens when the link lies?",
      heatBps: 7200,
      branchDepthCount: 2,
      meritBps: 4800,
      logBound: true,
      tags: {
        claims: ["Chain fields are grips, not decoration"],
        entities: ["receipt_hash", "dag_node_hash"],
        function: "evidence",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["provenance"],
      },
    }),
    scene({
      id: "e02",
      filmstripId: evidenceStrip,
      title: "Failure mode · orphan link",
      move: "rebuttal",
      durationSec: 60,
      parentSceneId: "s03",
      openHook: "The scar must show.",
      core: "If previous_receipt_hash points nowhere, the viewer labels broken — it does not invent continuity. That fail-closed posture is the difference between audit and mythology.",
      closeHook: "Deeper still: hash linkage edge cases.",
      heatBps: 8600,
      branchDepthCount: 2,
      forkCount: 1,
      branchFilmstripIds: [deepStrip],
      meritBps: 5700,
      tags: {
        claims: ["Broken links are labeled, never healed by UI"],
        entities: ["Fail-closed", "Provenance viewer"],
        function: "rebuttal",
        epistemic: "well_supported",
        temperature: "confrontational",
        domains: ["provenance", "kernel"],
      },
    }),
    scene({
      id: "e03",
      filmstripId: evidenceStrip,
      title: "Consent before memory",
      move: "assertion",
      durationSec: 47,
      parentSceneId: "s03",
      openHook: "No consent, no durable write.",
      core: "IW-2: unconsented append is noise. The filmstrip can preview forks; the Record only accepts gated writes.",
      closeHook: "Theatre proposes. Log disposes.",
      heatBps: 6900,
      meritBps: 5200,
      logBound: true,
      tags: {
        claims: ["Consent gates durable memory"],
        entities: ["IW-2", "Bailment consent"],
        function: "assertion",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["consent", "record"],
      },
    }),
    scene({
      id: "e04",
      filmstripId: evidenceStrip,
      title: "Return grip",
      move: "synthesis",
      durationSec: 40,
      parentSceneId: "s03",
      openHook: "Evidence branch closes.",
      core: "You can return to the parent filmstrip with orientation intact. Recursion without breadcrumbs is another form of gaslighting.",
      closeHook: "Pop the stack.",
      heatBps: 4100,
      meritBps: 2800,
      tags: {
        claims: ["Orientation is part of integrity"],
        entities: ["Breadcrumb path"],
        function: "synthesis",
        epistemic: "emerging",
        temperature: "synthetic",
        domains: ["ux", "integrity"],
      },
    }),
  ]) {
    scenes[s.id] = s;
  }

  for (const s of [
    scene({
      id: "c01",
      filmstripId: captureStrip,
      title: "Access journalism as soft capture",
      move: "assertion",
      durationSec: 59,
      parentSceneId: "s05",
      openHook: "Proximity to power feels like insight.",
      core: "When access becomes the scarce good, inquiry bends. Permanent public record reduces the value of quiet revision among insiders.",
      closeHook: "Chaos answers poorly — but answers.",
      heatBps: 6400,
      meritBps: 4000,
      tags: {
        claims: ["Access incentives bend inquiry"],
        entities: ["Corporate media", "Access"],
        function: "assertion",
        epistemic: "contested",
        temperature: "analytical",
        domains: ["press"],
      },
    }),
    scene({
      id: "c02",
      filmstripId: captureStrip,
      title: "Flood as counterfeit freedom",
      move: "reframe",
      durationSec: 63,
      parentSceneId: "s05",
      openHook: "Volume is not liberty.",
      core: "Low-rigor assertion dressed as investigation burns attention. Merit and Log binding are structural filters — not tribal censors.",
      closeHook: "Middle path next.",
      heatBps: 7000,
      forkCount: 1,
      meritBps: 4500,
      tags: {
        claims: ["Noise is not free expression’s ally"],
        entities: ["Merit", "Standards"],
        function: "reframe",
        epistemic: "contested",
        temperature: "confrontational",
        domains: ["merit", "press"],
      },
    }),
    scene({
      id: "c03",
      filmstripId: captureStrip,
      title: "Harder middle",
      move: "synthesis",
      durationSec: 51,
      parentSceneId: "s05",
      openHook: "Free. Rigorous. Permanent.",
      core: "intelwar.press names the posture; .tv makes the contest watchable and forkable. Neither replaces the Log.",
      closeHook: "Return upward.",
      heatBps: 5800,
      meritBps: 4900,
      tags: {
        claims: ["Structure over tribe"],
        entities: ["intelwar.press", "intelwar.tv"],
        function: "synthesis",
        epistemic: "well_supported",
        temperature: "synthetic",
        domains: ["press", "theatre"],
      },
    }),
  ]) {
    scenes[s.id] = s;
  }

  for (const s of [
    scene({
      id: "h01",
      filmstripId: histStrip,
      title: "Pre-digital vanishing",
      move: "evidence",
      durationSec: 57,
      parentSceneId: "s02",
      openHook: "The file cabinet could forget.",
      core: "Paper archives burned, classified, or simply lost. Digital feeds accelerated selective memory without inventing the problem.",
      closeHook: "Then came the infinite rewrite.",
      heatBps: 5600,
      meritBps: 3200,
      tags: {
        claims: ["Erasure predates the feed"],
        entities: ["Archives"],
        function: "evidence",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["history"],
      },
    }),
    scene({
      id: "h02",
      filmstripId: histStrip,
      title: "Platform memory as privilege",
      move: "assertion",
      durationSec: 55,
      parentSceneId: "s02",
      openHook: "Who holds the delete key?",
      core: "Corporate platforms exercise memory as product policy. Constitutional speech protection does not automatically yield durable public record.",
      closeHook: "Cryptographic permanence is a structural reply.",
      heatBps: 6700,
      meritBps: 4100,
      tags: {
        claims: ["Platform delete is not due process for history"],
        entities: ["Platforms", "First Amendment"],
        function: "assertion",
        epistemic: "contested",
        temperature: "confrontational",
        domains: ["press", "record"],
      },
    }),
    scene({
      id: "h03",
      filmstripId: histStrip,
      title: "Why the Log is the defense",
      move: "synthesis",
      durationSec: 46,
      parentSceneId: "s02",
      openHook: "Not nostalgia — structure.",
      core: "The Living Log does not declare official truth. It makes contested expression harder to gaslight out of existence.",
      closeHook: "Pop back to the root strip.",
      heatBps: 6100,
      meritBps: 4600,
      logBound: true,
      tags: {
        claims: ["Permanence defends inquiry"],
        entities: ["Living Log"],
        function: "synthesis",
        epistemic: "well_supported",
        temperature: "synthetic",
        domains: ["record"],
      },
    }),
  ]) {
    scenes[s.id] = s;
  }

  for (const s of [
    scene({
      id: "d01",
      filmstripId: deepStrip,
      title: "Ambiguous tip of chain",
      move: "evidence",
      durationSec: 44,
      parentSceneId: "e02",
      openHook: "Depth two. Still oriented.",
      core: "Genesis entries have null previous. Ambiguity begins when a mid-chain hash collides with a deleted or withheld node. Label, do not invent.",
      closeHook: "One more move.",
      heatBps: 7300,
      meritBps: 5000,
      tags: {
        claims: ["Null previous is genesis, not failure"],
        entities: ["Genesis entry"],
        function: "evidence",
        epistemic: "well_supported",
        temperature: "analytical",
        domains: ["provenance"],
      },
    }),
    scene({
      id: "d02",
      filmstripId: deepStrip,
      title: "Recursive integrity",
      move: "synthesis",
      durationSec: 42,
      parentSceneId: "e02",
      openHook: "You went deep on purpose.",
      core: "Recursive filmstrip design must preserve orientation and Log honesty at every depth. That is the product — not infinite scroll of vibes.",
      closeHook: "Climb back when ready.",
      heatBps: 5900,
      meritBps: 4400,
      tags: {
        claims: ["Depth without orientation is gaslighting"],
        entities: ["Filmstrip", "Breadcrumbs"],
        function: "synthesis",
        epistemic: "emerging",
        temperature: "synthetic",
        domains: ["ux", "integrity"],
      },
    }),
  ]) {
    scenes[s.id] = s;
  }

  return { strips, scenes, rootId };
}
