#!/usr/bin/env python3
# Copyright 2026 Exochain Foundation
# SPDX-License-Identifier: Apache-2.0

"""Regression tests for publishing immutable Cargo package archives."""

from __future__ import annotations

import gzip
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import ssl
import struct
import tarfile
import tempfile
import unittest
from unittest import mock


REPO_ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = REPO_ROOT / "tools" / "publish_sealed_crate.py"
SPEC = importlib.util.spec_from_file_location("publish_sealed_crate", MODULE_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("could not load sealed crate publisher")
PUBLISHER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(PUBLISHER)

CRATE = "exochain-fixture"
VERSION = "0.2.6"
COMMIT = "4" * 40


def tar_member(name: str, payload: bytes, *, member_type: bytes | None = None) -> tarfile.TarInfo:
    member = tarfile.TarInfo(name)
    member.mode = 0o644
    member.uid = member.gid = member.mtime = 0
    member.uname = member.gname = ""
    member.size = len(payload)
    if member_type is not None:
        member.type = member_type
    return member


def archive_bytes(
    *,
    crate: str = CRATE,
    version: str = VERSION,
    commit: str = COMMIT,
    duplicate_manifest: bool = False,
    ambiguous_manifest: bool = False,
    ambiguous_readme: bool = False,
    unsafe_member: bool = False,
) -> bytes:
    prefix = f"{crate}-{version}"
    manifest = f'''# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
[package]
name = "{crate}"
version = "{version}"
authors = ["EXOCHAIN <security@exochain.com>"]
description = "sealed upload fixture"
documentation = "https://docs.rs/{crate}"
homepage = "https://exochain.com"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/exochain/exochain"
links = "fixture-native"
rust-version = "1.85"
publish = true

[features]
default = ["dep:serde"]
fixture = ["serde/derive"]

[dependencies.renamed-serde]
version = "=1.0.228"
features = ["derive"]
optional = true
default-features = false
package = "serde"

[dev-dependencies.proptest]
version = "=1.9.0"

[build-dependencies.cc]
version = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies.js-sys]
version = "=0.3.81"
'''.encode()
    vcs = json.dumps(
        {"git": {"sha1": commit}, "path_in_vcs": "crates/fixture"},
        separators=(",", ":"),
    ).encode()
    files = [
        (f"{prefix}/.cargo_vcs_info.json", vcs, None),
        (f"{prefix}/Cargo.lock", b"version = 4\n", None),
        (f"{prefix}/Cargo.toml", manifest, None),
        (f"{prefix}/Cargo.toml.orig", manifest, None),
        (f"{prefix}/README.md", b"# Sealed fixture\n", None),
        (f"{prefix}/src/lib.rs", b"pub fn fixture() {}\n", None),
    ]
    if duplicate_manifest:
        files.append((f"{prefix}/Cargo.toml", manifest, None))
    if ambiguous_manifest:
        files.append((f"{prefix}/./Cargo.toml", b"attacker replacement", None))
    if ambiguous_readme:
        files.append((f"{prefix}/./README.md", b"# Sealed fixture\n", None))
    if unsafe_member:
        files.append((f"{prefix}/link", b"target", tarfile.SYMTYPE))

    raw_tar = io.BytesIO()
    with tarfile.open(fileobj=raw_tar, mode="w", format=tarfile.USTAR_FORMAT) as archive:
        for name, payload, member_type in files:
            archive.addfile(tar_member(name, payload, member_type=member_type), io.BytesIO(payload))
    compressed = io.BytesIO()
    with gzip.GzipFile(fileobj=compressed, mode="wb", mtime=0) as output:
        output.write(raw_tar.getvalue())
    return compressed.getvalue()


class FakeResponse:
    def __init__(self, status: int, payload: bytes, reason: str = "fixture") -> None:
        self.status = status
        self.reason = reason
        self._payload = payload

    def read(self, amount: int) -> bytes:
        return self._payload[:amount]


class FakeConnection:
    def __init__(self, response: FakeResponse, mutate=None) -> None:
        self.response = response
        self.mutate = mutate
        self.request_record = None
        self.closed = False

    def request(self, method, path, *, body, headers) -> None:
        if self.mutate is not None:
            self.mutate()
        self.request_record = (method, path, body, headers)

    def getresponse(self) -> FakeResponse:
        return self.response

    def close(self) -> None:
        self.closed = True


class ConnectionFactory:
    def __init__(self, connection: FakeConnection) -> None:
        self.connection = connection
        self.calls = []

    def __call__(self, host, port, *, timeout, context):
        self.calls.append((host, port, timeout, context))
        return self.connection


class SealedCratePublisherTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory(prefix="sealed-crate-test-")
        self.root = Path(self.temp.name)
        self.archive = self.root / f"{CRATE}-{VERSION}.crate"
        self.original = archive_bytes()
        self.archive.write_bytes(self.original)
        self.digest = hashlib.sha256(self.original).hexdigest()

    def tearDown(self) -> None:
        self.temp.cleanup()

    def load(self):
        return PUBLISHER.load_sealed_crate(
            self.archive,
            expected_crate=CRATE,
            expected_version=VERSION,
            expected_sha256=self.digest,
            expected_commit=COMMIT,
        )

    def test_request_body_contains_exact_archive_and_complete_metadata(self) -> None:
        sealed = self.load()
        body = sealed.request_body
        metadata_size = struct.unpack_from("<I", body, 0)[0]
        metadata_start = 4
        metadata_end = metadata_start + metadata_size
        metadata = json.loads(body[metadata_start:metadata_end])
        archive_size = struct.unpack_from("<I", body, metadata_end)[0]
        embedded_archive = body[metadata_end + 4 :]

        self.assertEqual(archive_size, len(self.original))
        self.assertEqual(embedded_archive, self.original)
        self.assertEqual(metadata, sealed.metadata)
        self.assertEqual(metadata["name"], CRATE)
        self.assertEqual(metadata["vers"], VERSION)
        self.assertEqual(metadata["readme"], "# Sealed fixture\n")
        self.assertEqual(metadata["readme_file"], "README.md")
        self.assertEqual(metadata["rust_version"], "1.85")
        self.assertEqual(metadata["features"]["fixture"], ["serde/derive"])
        self.assertEqual(
            metadata["deps"],
            [
                {
                    "default_features": True,
                    "features": [],
                    "kind": "build",
                    "name": "cc",
                    "optional": False,
                    "target": None,
                    "version_req": "^1",
                },
                {
                    "default_features": True,
                    "features": [],
                    "kind": "dev",
                    "name": "proptest",
                    "optional": False,
                    "target": None,
                    "version_req": "=1.9.0",
                },
                {
                    "default_features": False,
                    "explicit_name_in_toml": "renamed-serde",
                    "features": ["derive"],
                    "kind": "normal",
                    "name": "serde",
                    "optional": True,
                    "target": None,
                    "version_req": "=1.0.228",
                },
                {
                    "default_features": True,
                    "features": [],
                    "kind": "normal",
                    "name": "js-sys",
                    "optional": False,
                    "target": "cfg(target_arch = \"wasm32\")",
                    "version_req": "=0.3.81",
                },
            ],
        )

    def test_path_mutation_after_memory_seal_cannot_change_request(self) -> None:
        connection = FakeConnection(
            FakeResponse(200, b'{"warnings":{"invalid_categories":[],"invalid_badges":[],"other":[]}}'),
            mutate=lambda: self.archive.write_bytes(b"attacker replacement"),
        )
        factory = ConnectionFactory(connection)
        result = PUBLISHER.publish_sealed_crate(
            self.archive,
            expected_crate=CRATE,
            expected_version=VERSION,
            expected_sha256=self.digest,
            expected_commit=COMMIT,
            token="fixture-token",
            connection_factory=factory,
        )
        self.assertEqual(result["warnings"]["other"], [])
        self.assertEqual(factory.calls[0][0:3], ("crates.io", 443, 120))
        self.assertIsInstance(factory.calls[0][3], ssl.SSLContext)
        method, path, body, headers = connection.request_record
        self.assertEqual((method, path), ("PUT", "/api/v1/crates/new"))
        self.assertEqual(headers["Authorization"], "fixture-token")
        embedded_size_offset = 4 + struct.unpack_from("<I", body, 0)[0]
        self.assertEqual(body[embedded_size_offset + 4 :], self.original)
        self.assertTrue(connection.closed)

    def test_invalid_archive_never_opens_a_network_connection(self) -> None:
        self.archive.write_bytes(b"changed")
        factory = ConnectionFactory(FakeConnection(FakeResponse(200, b"{}")))
        with self.assertRaises(PUBLISHER.SealedCrateError):
            PUBLISHER.publish_sealed_crate(
                self.archive,
                expected_crate=CRATE,
                expected_version=VERSION,
                expected_sha256=self.digest,
                expected_commit=COMMIT,
                token="fixture-token",
                connection_factory=factory,
            )
        self.assertEqual(factory.calls, [])

    def test_archive_identity_and_file_type_fail_closed(self) -> None:
        cases = []
        cases.append(("wrong checksum", {"expected_sha256": "0" * 64}))
        cases.append(("wrong crate", {"expected_crate": "exochain-other"}))
        cases.append(("wrong version", {"expected_version": "0.2.5"}))
        cases.append(("wrong commit", {"expected_commit": "5" * 40}))
        for label, override in cases:
            arguments = {
                "expected_crate": CRATE,
                "expected_version": VERSION,
                "expected_sha256": self.digest,
                "expected_commit": COMMIT,
            }
            arguments.update(override)
            with self.subTest(label=label), self.assertRaises(PUBLISHER.SealedCrateError):
                PUBLISHER.load_sealed_crate(self.archive, **arguments)

        symlink = self.root / "symlink.crate"
        symlink.symlink_to(self.archive)
        with self.assertRaises(PUBLISHER.SealedCrateError):
            PUBLISHER.load_sealed_crate(
                symlink,
                expected_crate=CRATE,
                expected_version=VERSION,
                expected_sha256=self.digest,
                expected_commit=COMMIT,
            )

        hardlink_target = self.root / "hardlink-target"
        hardlink_target.write_bytes(self.original)
        os.replace(hardlink_target, self.archive)
        second_link = self.root / "second-link"
        os.link(self.archive, second_link)
        with self.assertRaises(PUBLISHER.SealedCrateError):
            self.load()

        second_link.unlink()
        with self.archive.open("wb") as oversized:
            oversized.truncate(PUBLISHER.MAX_CRATE_BYTES + 1)
        with self.assertRaises(PUBLISHER.SealedCrateError):
            PUBLISHER.load_sealed_crate(
                self.archive,
                expected_crate=CRATE,
                expected_version=VERSION,
                expected_sha256="0" * 64,
                expected_commit=COMMIT,
            )

    def test_duplicate_and_non_regular_members_fail_closed(self) -> None:
        for label, payload in (
            ("duplicate", archive_bytes(duplicate_manifest=True)),
            ("ambiguous", archive_bytes(ambiguous_manifest=True)),
            ("symlink", archive_bytes(unsafe_member=True)),
        ):
            path = self.root / f"{label}-{CRATE}-{VERSION}.crate"
            path.write_bytes(payload)
            expected_path = self.root / f"{CRATE}-{VERSION}.crate"
            os.replace(path, expected_path)
            with self.subTest(label=label), self.assertRaises(PUBLISHER.SealedCrateError):
                PUBLISHER.load_sealed_crate(
                    expected_path,
                    expected_crate=CRATE,
                    expected_version=VERSION,
                    expected_sha256=hashlib.sha256(payload).hexdigest(),
                    expected_commit=COMMIT,
                )

    def test_archive_paths_must_already_be_canonical(self) -> None:
        for value in ("crates//fixture", "crates/./fixture", "./crates/fixture"):
            with self.subTest(value=value), self.assertRaises(PUBLISHER.SealedCrateError):
                PUBLISHER.safe_archive_relative_path(value, "fixture path")

    def test_archive_reader_fails_closed_without_nofollow_support(self) -> None:
        with mock.patch.object(PUBLISHER.os, "O_NOFOLLOW", 0):
            with self.assertRaises(PUBLISHER.SealedCrateError):
                self.load()

    def test_http_redirect_errors_duplicate_json_and_oversize_fail_closed(self) -> None:
        cases = (
            (302, b"redirect"),
            (200, b'{"errors":[{"detail":"rejected"}]}'),
            (200, b'{"warnings":{},"warnings":{}}'),
            (200, b"{" + b" " * (PUBLISHER.MAX_RESPONSE_BYTES + 1)),
        )
        for status, payload in cases:
            connection = FakeConnection(FakeResponse(status, payload))
            with self.subTest(status=status, payload=payload[:20]), self.assertRaises(
                PUBLISHER.SealedCrateError
            ):
                PUBLISHER.publish_sealed_crate(
                    self.archive,
                    expected_crate=CRATE,
                    expected_version=VERSION,
                    expected_sha256=self.digest,
                    expected_commit=COMMIT,
                    token="fixture-token",
                    connection_factory=ConnectionFactory(connection),
                )

    def test_sparse_success_responses_follow_cargo_semantics(self) -> None:
        accepted = (
            b"",
            b"{}",
            b'{"warnings":{}}',
            b'{"warnings":{"other":["delayed index"]}}',
        )
        for payload in accepted:
            connection = FakeConnection(FakeResponse(200, payload))
            with self.subTest(payload=payload):
                result = PUBLISHER.publish_sealed_crate(
                    self.archive,
                    expected_crate=CRATE,
                    expected_version=VERSION,
                    expected_sha256=self.digest,
                    expected_commit=COMMIT,
                    token="fixture-token",
                    connection_factory=ConnectionFactory(connection),
                )
                self.assertEqual(result["warnings"]["invalid_categories"], [])
                self.assertEqual(result["warnings"]["invalid_badges"], [])
                self.assertIsInstance(result["warnings"]["other"], list)

    def test_unrecognized_dependency_requirement_fails_closed(self) -> None:
        self.assertEqual(PUBLISHER.canonical_version_requirement("0.19", "fixture"), "^0.19")
        self.assertEqual(PUBLISHER.canonical_version_requirement("=0.1.0-rc.7", "fixture"), "=0.1.0-rc.7")
        for requirement in ("^1", ">=1", "*", "1 || 2"):
            with self.subTest(requirement=requirement), self.assertRaises(
                PUBLISHER.SealedCrateError
            ):
                PUBLISHER.canonical_version_requirement(requirement, "fixture")

    def test_http_429_is_a_distinct_bounded_retry_signal(self) -> None:
        connection = FakeConnection(FakeResponse(429, b'{"errors":[{"detail":"slow down"}]}'))
        with self.assertRaises(PUBLISHER.CratesIoHttpError) as raised:
            PUBLISHER.publish_sealed_crate(
                self.archive,
                expected_crate=CRATE,
                expected_version=VERSION,
                expected_sha256=self.digest,
                expected_commit=COMMIT,
                token="fixture-token",
                connection_factory=ConnectionFactory(connection),
            )
        self.assertEqual(raised.exception.status, 429)

    def test_tls_or_transport_failure_is_not_retried_inside_uploader(self) -> None:
        calls = 0

        def failing_factory(*_args, **_kwargs):
            nonlocal calls
            calls += 1
            raise ssl.SSLError("fixture TLS failure")

        with self.assertRaises(PUBLISHER.SealedCrateError):
            PUBLISHER.publish_sealed_crate(
                self.archive,
                expected_crate=CRATE,
                expected_version=VERSION,
                expected_sha256=self.digest,
                expected_commit=COMMIT,
                token="fixture-token",
                connection_factory=failing_factory,
            )
        self.assertEqual(calls, 1)


if __name__ == "__main__":
    unittest.main()
